sub:
  - http://wxshi.top:9090/clash/proxies
  - http://39.106.12.141:8081/clash/proxies
  - http://101.132.255.205:1234/clash/proxies
  - http://139.196.162.200:9090/clash/proxies
  - http://proxypool.918848.xyz/clash/proxies
  - http://101.132.255.205:1234/clash/proxies
  - https://pc.adlionvm.tk/clash/proxies
  - https://proxies.bihai.cf/clash/proxies
  - https://klausvpn.posyao.com/clash/proxies
  - https://sspool.herokuapp.com/clash/proxies
  - https://proxypool.laowang.me/clash/proxies
  - https://free886.herokuapp.com/clash/proxies
  - https://us-proxypool.herokuapp.com/clash/proxies
  - https://eu-proxypool.herokuapp.com/clash/proxies
  - https://proxy.yiun.xyz/clash/proxies
  - https://us-proxypool.herokuapp.com/clash/proxies
  - https://proxies.bihai.cf/clash/proxies
  - https://free.jingfu.cf/clash/proxies
  - https://sspool.herokuapp.com/clash/proxies
  - https://pool.jinxnet.xyz/clash/proxies
  - http://121.37.67.232/clash/proxies
  - https://free.iam7.tk/clash/proxies
  - http://168.138.45.251/clash/proxies
  - https://jdc666.littlesite.ml/clash/proxies
  - https://raw.githubusercontent.com/LITTLESITE/openit/main/pool/output.yaml #回环订阅
  - https://raw.githubusercontent.com/LITTLESITE/openit/main/utils/pool/pool.yaml #入库订阅
  
